#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2026 - Present Sepine Tam, Inc. All Rights Reserved
#
# @Author : Sepine Tam (谭淞)
# @Email  : sepinetam@gmail.com
# @File   : db/__init__.py

"""Database and info-cache subpackage."""

from __future__ import annotations

from .db import (
    NBER_CLI_DIR_NAME,
    NBER_CLI_CONFIG_NAME,
    NBER_DB_NAME,
    LEGACY_DB_NAME,
    SCHEMA_VERSION,
    _validate_db_path,
    init_database,
    migrate_database,
    get_database_path,
    get_schema_version,
    _ensure_full_schema,
    _ensure_full_schema_on_engine,
    _ensure_full_schema_on_connection,
    _upgrade_v1_to_v2,
    _upgrade_v2_to_v3,
    _reject_future_schema,
    _begin_schema_transaction,
    _create_all_tables,
    _read_user_version,
    _write_config,
    _configured_db_path,
    _read_config,
    _default_config_path,
    _default_db_path,
    _legacy_db_path,
    _normalize_db_path,
    _path_from_sqlite_url,
    _database_url_from_path,
    _create_engine,
    create_engine,
    _open_session,
    _execute,
    _db_move_pairs,
    read_paper_read_status,
    set_paper_read_status,
    _coerce_db_bool,
    record_query,
    record_download,
    record_info,
    read_info_cache,
    is_info_cache_enabled,
    get_info_cache_ttl_days,
    is_info_cache_expired,
    write_info_cache,
    touch_info_cache,
    count_info_cache,
    clear_info_cache,
    _build_info_cache_clear_condition,
    _build_info_cache_date_condition,
    _parse_cache_date,
    _parse_cached_datetime,
    _utc_now,
    _paper_id_to_str,
    _paper_id_from_str,
    _normalize_paper_id,
    _log_warning,
)
from .info_cache import get_paper_with_info_cache, get_paper_with_info_cache_result

__all__ = [
    "NBER_CLI_DIR_NAME",
    "NBER_CLI_CONFIG_NAME",
    "NBER_DB_NAME",
    "LEGACY_DB_NAME",
    "SCHEMA_VERSION",
    "_validate_db_path",
    "init_database",
    "migrate_database",
    "get_database_path",
    "get_schema_version",
    "_ensure_full_schema",
    "_ensure_full_schema_on_engine",
    "_ensure_full_schema_on_connection",
    "_upgrade_v1_to_v2",
    "_upgrade_v2_to_v3",
    "_reject_future_schema",
    "_begin_schema_transaction",
    "_create_all_tables",
    "_read_user_version",
    "_write_config",
    "_configured_db_path",
    "_read_config",
    "_default_config_path",
    "_default_db_path",
    "_legacy_db_path",
    "_normalize_db_path",
    "_path_from_sqlite_url",
    "_database_url_from_path",
    "_create_engine",
    "create_engine",
    "_open_session",
    "_execute",
    "_db_move_pairs",
    "read_paper_read_status",
    "set_paper_read_status",
    "_coerce_db_bool",
    "record_query",
    "record_download",
    "record_info",
    "read_info_cache",
    "is_info_cache_enabled",
    "get_info_cache_ttl_days",
    "is_info_cache_expired",
    "write_info_cache",
    "touch_info_cache",
    "count_info_cache",
    "clear_info_cache",
    "_build_info_cache_clear_condition",
    "_build_info_cache_date_condition",
    "_parse_cache_date",
    "_parse_cached_datetime",
    "_utc_now",
    "_paper_id_to_str",
    "_paper_id_from_str",
    "_normalize_paper_id",
    "_log_warning",
    "get_paper_with_info_cache",
    "get_paper_with_info_cache_result",
]
